server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:otus}
    username: postgres
    password: root
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration