apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: hw
  labels:
    app: {{ .Values.app.name }}
data:
  POSTGRES_PASSWORD: {{ .Values.database.pass }}
stringData:
  POSTGRES_USER: {{ .Values.database.user }}
type: Opaque