kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-pv-volume
  namespace: hw
  labels:
    type: local
    app: {{ .Values.app.name }}
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-pv-claim
  namespace: hw
  labels:
    app: {{ .Values.app.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi