apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: hw
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}-config
            - secretRef:
                name: {{ .Values.app.name }}-secret
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
            - name: pg-secret
              mountPath: /etc/pg
              readOnly: true
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-pv-claim
        - name: pg-secret
          secret:
            secretName: {{ .Values.app.name }}-secret