apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: hw
  labels:
    app: {{ .Values.app.name }}
spec:
  type: LoadBalancer
  ports:
   - port: 5432
     protocol: TCP
  selector:
   app: {{ .Values.app.name }}